language: python
python:
- 'pypy3'
- 'pypy'
- '3.4'
- '3.3'
- '3.2'
- '2.7'
install:
- travis_retry pip install -r requirements.txt
- travis_retry pip install -r test-requirements.txt
script: nosetests